= Parameters

The parent key for all of the following parameters is `steward`.

== `namespace`

[horizontal]
type:: string
default:: `syn`

The namespace in which to deploy this component.

NOTE: This component doesn't create the provided namespace.

== `api_url`

[horizontal]
type:: string
default:: `https://api.syn.vshn.net/docs[https://api.syn.vshn.net/]`

The URL of the Lieutenant API to which Steward should connect.

== `token`

[horizontal]
type:: string
default:: `?{vaultkv:${cluster:tenant}/${cluster:name}/steward/token}`

The API token for the Lieutenant API to which Steward should connect.
By default, the component is configured to fetch the API token from Vault.

== `resources`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
requests:
  cpu: 100m
  memory: 32Mi
limits:
  cpu: 200m
  memory: 64Mi
----

This parameter allows users to configure the resource requests and limits for the Steward pod.

NOTE: The provided value isn't validated and is used directly as the container's `resources`.

== `images`

[horizontal]
type:: dict
defaults:: https://github.com/projectsyn/component-steward/blob/master/class/defaults.yml[See `class/defaults.yml`]

The Steward and ArgoCD container image versions which the component should use.

== `additional_facts`

[horizontal]
type:: dict
default:: `{}`
example::
+
[source,yaml]
----
additional_facts:
  myIdFromHierarchy: mx7bMF3VIfVpGhMZDnoW65oG08Wv9ICYXetH5DNM
  glusterVersion:
    major: 11
    minor: 1
----

Additional facts to be added to the dynamic facts Steward provides to Lieutenant.
Objects are serialized to JSON.
Dynamic facts implemented in Steward can't be overridden.

== Example

[source,yaml]
----
api_url: 'https://lieutenant.example.com'
resources:
  requests:
    cpu: 200m
    memory: 34Mi
  limits:
    cpu: 200m
    memory: 64Mi
----
